# Generated by Django 3.0.6 on 2020-05-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=200, verbose_name='post name')),
                ('post_text', models.TextField(verbose_name='post text')),
                ('post_pubdate', models.DateTimeField(verbose_name='publicate data')),
            ],
        ),
    ]
