# Generated by Django 3.0.6 on 2020-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_curse_curse_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='curse',
            name='curse_id',
            field=models.IntegerField(default=0, verbose_name='ID(look latest curse id and write next number)'),
        ),
    ]
