# Generated by Django 3.0.6 on 2020-06-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_lesson_les_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nofication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nof_date', models.DateTimeField(verbose_name='Дата')),
                ('nof_username', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('nof_email', models.CharField(max_length=250, verbose_name='Email')),
                ('nof_text', models.TextField(verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.AlterModelOptions(
            name='curse',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='cursebuy',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='curse',
            name='curse_cost',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='curse',
            name='curse_descr',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='curse',
            name='curse_id',
            field=models.IntegerField(default=0, verbose_name='ID(посмотри ID последнего курса и напиши следущее число(ЭТО ВАЖНО))'),
        ),
        migrations.AlterField(
            model_name='curse',
            name='curse_img',
            field=models.ImageField(default=None, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='curse',
            name='curse_name',
            field=models.CharField(max_length=200, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='curse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Curse', verbose_name='Для курса...'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='les_descr',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='les_googlelink',
            field=models.CharField(blank=True, max_length=250, verbose_name='Google disk ссылка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='les_id',
            field=models.IntegerField(default=1, verbose_name='Номер урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='les_title',
            field=models.CharField(max_length=200, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='les_youtubelink',
            field=models.CharField(blank=True, max_length=250, verbose_name='Youtube ссылка'),
        ),
    ]
