# Generated by Django 3.0.6 on 2020-06-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200602_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curse',
            name='curse_img',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
