# Generated by Django 3.0.6 on 2020-06-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_nofication_nof_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nofication',
            name='nof_email',
            field=models.CharField(blank=True, max_length=250, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='nofication',
            name='nof_username',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя пользователя'),
        ),
    ]
