# Generated by Django 3.0.6 on 2020-06-05 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20200602_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_text', models.TextField(verbose_name='Текст коментария')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Коментатор')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Lesson', verbose_name='Урок')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_text', models.TextField(verbose_name='Текст коментария')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Коментатор')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Lesson', verbose_name='Урок')),
                ('pr_comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Comment', verbose_name='Родитель ком.')),
            ],
        ),
    ]
