# Generated by Django 3.0.6 on 2020-06-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_comment_commentreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nofication',
            name='nof_email',
        ),
        migrations.RemoveField(
            model_name='nofication',
            name='nof_username',
        ),
    ]
