# Generated by Django 3.0.6 on 2020-06-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200606_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='pr_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Comment', verbose_name='Родитель ком.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='les_id',
            field=models.IntegerField(default=1, verbose_name='ID(посмотри ID последнего курса и напиши следущее число(ЭТО ВАЖНО))'),
        ),
    ]
